### ISSUE TITLE
Fix README issues.

### ISSUE THREAD

**Issue by krisblarq** [Greenstand/treetracker-api#120] opened 2022-11-09 18:44 UTC
I noticed the following issues on the README;

1. A typo on migrating db - "cd datbaase" should be cd database.
2. The link to the postman API spec is broken (404 error).

**Comment by Kpoke** [comment] 2023-01-16 21:37
The readme is massively out of date and should be based off of https://github.com/Greenstand/treetracker-microservice-template/blob/main/README.md

**Comment by Kpoke** [comment] 2023-01-17 05:21
duplicate of #27

**Closed by Kpoke** 2023-01-17 05:21 UTC
